from time import sleep
import pyautogui
import webbrowser
def sai():
    pyautogui.moveTo(1484,203,duration=1)
    pyautogui.click()
    sleep(1)
    pyautogui.click()
    pyautogui.moveTo(2272,186,duration=1)
    pyautogui.click()
    sleep(1)
    pyautogui.moveTo(2262,117,duration=1)
    pyautogui.click()
    pyautogui.moveTo(2038,624,duration=1)
    pyautogui.click()


webbrowser.open("www.instagram.com")
while True:
    sleep(3)
    pyautogui.moveTo(2117,274,duration=1)
    pyautogui.click(button="left")
    pyautogui.typewrite("gmail")
    sleep(2)
    pyautogui.moveTo(2116,315,duration=1)
    pyautogui.click(button="left")
    sleep(2)
    pyautogui.typewrite("senha")
    sleep(1)
    pyautogui.moveTo(2210,365,duration=1)
    sleep(1)
    pyautogui.click()
    sleep(4)
    pyautogui.moveTo(2167,446,duration=1)
    pyautogui.click()
    sleep(2)
    pyautogui.moveTo(1462,261,duration=1)
    pyautogui.click()
    pyautogui.moveTo(1496,181,duration=1)
    pyautogui.click()
    pyautogui.typewrite("nike")
    sleep(2)
    pyautogui.moveTo(1530,271,duration=1)
    pyautogui.click()
    sleep(2)
    pyautogui.moveTo(1832,650,duration=1)
    pyautogui.click()
    cora = pyautogui.locateCenterOnScreen("print da imagem.png")
    sleep(1)
    if cora is not None:
        sai()
        sleep(15)
    elif cora == None:
        pyautogui.moveTo(1972,560,duration=1)
        sleep(1)
        pyautogui.click()
        pyautogui.moveTo(2018,564,duration=1)
        pyautogui.click()
        pyautogui.moveTo(2049,677,duration=1)

        sleep(1)
        pyautogui.typewrite("gostei muito")
        sai()
        sleep(10)